USE breweries_DB;

INSERT INTO breweries (breweryName, region, fullAddress, fullDescription, website, photo, phone, latitude, longitude)
VALUES ("Rueben's Brewery", "Ballard", "5010 14th Ave NW, Seattle, WA 98107", "We're an award winning microbrewery focused on making small batches of top quality ales and lagers. We're family owned and focused on brewing unconstrained to make the best beer possible.", "www.reubensbrews.com/", "http://via.placeholder.com/500x400", "(206) 784-2859", "47.6653", "-122.373");

INSERT INTO breweries (breweryName, region, fullAddress, fullDescription, website, photo, phone, latitude, longitude)
VALUES ("Stoup Brewing", "Ballard", "1108 NW 52nd St, Seattle, WA 98107", "Stoup's beers are beautifully balanced from start to finish, which makes sense given certified-Cicerone Robyn Schumacher's contributions to the team. Stoup's best bets are the award-winning robust porter, excellent year-round, and the sour Berliner Weisse with a shot of flavored syrup.", "www.stoupbrewing.com/", "http://via.placeholder.com/500x400", "(206) 457-5524", "47.666703", "-122.371206");

INSERT INTO breweries (breweryName, region, fullAddress, fullDescription, website, photo, phone, latitude, longitude)
VALUES ("Populuxe Brewery", "Ballard", "826 NW 49th St, Seattle, WA 98107", "Co-founders Peter Charbonnier and Amy Besunder started Populuxe Brewing in 2012. Peter had been a home brewer for many years and as his brewing equipment began to outgrow their garage, they began to seek out a commercial space.They found a slightly larger garage within two blocks of their longtime home in Ballard and after 8 months of rushing home after work to do demo and construction, filling out paperwork with various government agencies, piecing together furnishings and basically DYI'ing together a brewery, they opened the doors to their nanobrewery", "https://www.populuxebrewing.com/", "http://via.placeholder.com/500x400", "(206) 706-3400", "47.664636", "-122.367502")